### ISSUE TITLE
Checksums for reusable workflows

### ISSUE THREAD

**Issue by ericcornelissen** [chains-project/ghasum#215]
Relates to #49 

## Summary

Per the [GitHub Actions workflow syntax documentation](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses) it is possible to re-use workflows. This means that you can load a workflow from another repository and run that. This process is similar to using a GitHub Action, it pulls in an external artifact and executes it. Therefor, if the workflow is external, it should be included in the `gha.sum` file and verified automatically.

## Example

Consider the workflow (example from the docs):

```yaml
jobs:
  call-workflow-in-another-repo:
    uses: octo-org/another-repo/.github/workflows/workflow.yml@v1
```

this should be covered by including the checksum of the repository `octo-org/another-repo` at the ref `v1` in the `gha.sum` file.
